# Generated by Django 5.1.7 on 2025-04-01 00:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField()),
                ('success', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='recognition_logs/')),
                ('processing_time', models.FloatField(blank=True, help_text='Recognition processing time in seconds', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
